### ISSUE TITLE
Scholar Whispering Dawn not being used (In Auto)

### ISSUE THREAD

**Issue by Solace9** [FFXIV-CombatReborn/RotationSolverReborn#109]
Keep in mind that i've not tested this in Manual, the settings are on default for me (No condition set) 
![WHdA7hj](https://github.com/FFXIV-CombatReborn/RotationSolverReborn/assets/167470284/bf29c88f-43b5-4fb2-966e-819fdad19853)

I'll just add the tooltip for the spell for reference.

**Comment by Tykku** [comment]
Stale Issue with DT release
