### ISSUE TITLE
Ninja - Below level 90 issues

### ISSUE THREAD

**Issue by alazymainwarrior** [FFXIV-CombatReborn/RotationSolverReborn#119]
- The Ninki Gauge has not been used to cast 'Bhavacakra' or 'Hellfrog Medium', which are the spells associated with it, since it was unlocked.
- RSR attempted to use the mudra 'Jin' while doing sub level 45 content, but it was not yet unlocked.

**Comment by Tykku** [comment]
Stale Issue since DT
