### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by ariapurple** [FFXIV-CombatReborn/RotationSolverReborn#120]
![image](https://github.com/FFXIV-CombatReborn/RotationSolverReborn/assets/29880339/cc48e637-1c88-4bd9-aa87-707f5e5b45f2)

When I install, it stuck at this screen, after stuck, it still showing "Install v4.1.0.1"
Other plugin after stuck will install success. Only Bossmod Reborn & RotationSolverReborn will failed.

Why this happen:
After updated FFXIV at 4/19, I try to update the plugin but pressed delete button, after that I keep this happen.

Tried:
Re-install FFXIV Lanucher
Re-install FFXIV Game
Remove plugin folder in AppData and re-install
Reboot computer
Reboot game

**Comment by Tykku** [comment]
Please reach out for help on the discord
