### ISSUE TITLE
Warrior - Inner release doesn't get used

### ISSUE THREAD

**Issue by Kery0x** [FFXIV-CombatReborn/RotationSolverReborn#13]
Hello.

I'm using rotation solver 4.0.0.1.
The last version I was using before worked fine.

On my warrior, inner release doesn't get used while fighting on manual or auto. I tried on mobs, duties and dummies.

There is a way to force use it if you're on manual for example. You start the fight, then click around to unselect the target and poof, inner release get used.

I also tried with my MCH on a variant dungeon (mount), Wildfire didn't get used at all on bosses neither.

**Comment by LTS-FFXIV** [comment]
Fixed

![image](https://github.com/FFXIV-CombatReborn/RotationSolverReborn/assets/127939494/5e91df37-54a6-4e12-b3d2-836d5035aa0a)
