### ISSUE TITLE
Timeline doesn't load macro properly

### ISSUE THREAD

**Issue by AppleCronch** [FFXIV-CombatReborn/RotationSolverReborn#137]
If you add a macro action in the timeline and then reload it changes into something else. This happens when restarting or copying and pasting from clipboard

**Comment by AppleCronch** [comment]
Here's a screenshot of what happens. 

Setting a macro in the timeline works. It executes fine during the fight.

![Screenshot 2024-05-24 201810](https://github.com/FFXIV-CombatReborn/RotationSolverReborn/assets/161672665/0af3205f-a4da-4bd0-b8e3-c895e47db48d)


But reload the game/copy paste from clipboard it turns into this
![Screenshot 2024-05-24 202100](https://github.com/FFXIV-CombatReborn/RotationSolverReborn/assets/161672665/7a42b96b-2585-486b-810e-fc9125219d69)

**Comment by Tykku** [comment]
Timeline has been removed and is pending a massive rework, closing stale issue.
