### ISSUE TITLE
Samurai - Yukikaze "hanging"

### ISSUE THREAD

**Issue by Deathbeyond87** [FFXIV-CombatReborn/RotationSolverReborn#16]
issue with LTS samurai rotation showing no "next skill" in the next skill window at Yukikaze in both single target and AoE scenarios. Periodic issue with it, not sure what exactly makes it reproducible. Possibly a hang where it wants to use Iaijutsu and using yukikaze would cause it to gain a sticker it already has, wasting gcd?

**Comment by LTS-FFXIV** [comment]
![image](https://github.com/FFXIV-CombatReborn/RotationSolverReborn/assets/127939494/188ea840-7432-4694-bd5b-5d2474397a1c)
fixed
