### ISSUE TITLE
[Bug] RSR making several thousands of the data cache tag "Avarice.ActionOverride"

### ISSUE THREAD

**Issue by BrakusTapus** [FFXIV-CombatReborn/RotationSolverReborn#169]
RSR version: v4.1.1.9

As soon as RSR is on thousands of these will be made until user either turns RSR off completely or closes the game.
Occurs when Avarice is not installed or is installed.
Is this intentional?

![image](https://github.com/FFXIV-CombatReborn/RotationSolverReborn/assets/38063721/92ca734a-6b86-4d95-811d-efafb3641051)
![ffxiv_dx11_Ij0U5wZP7h](https://github.com/FFXIV-CombatReborn/RotationSolverReborn/assets/38063721/55e14c36-c65f-434b-bf41-abe931258fc6)

**Comment by spaceelysian** [comment]
`private static void SetAction(uint id) => Svc.PluginInterface.GetOrCreateData( "Avarice.ActionOverride", ( ) => new List<uint>( ) {id} ) [0] = id;`

I think it has something to do with this bit of code. Is it because a new list is created every time?

**Comment by BrakusTapus** [comment]
> `private static void SetAction(uint id) => Svc.PluginInterface.GetOrCreateData( "Avarice.ActionOverride", ( ) => new List<uint>( ) {id} ) [0] = id;`
> 
> I think it has something to do with this bit of code. Is it because a new list is created every time?


Yeah it's creating a new list because of that line of code, the same bug was present in the orginal RS but has been fixed

https://github.com/ArchiDog1998/RotationSolver/pull/623

**Comment by NostraThomas99** [comment]
Fixed in #172
