### ISSUE TITLE
Feature Request: Keybinds

### ISSUE THREAD

**Issue by StrawberryClover** [FFXIV-CombatReborn/RotationSolverReborn#173]
I tend to toggle RSR a lot, sometimes I get distracted (say, at work) and just want it to take over for a sec, sometimes I am letting it run and I need to look away from a gaze mechanic but RSR keeps having me look back at the target I am fighting, would love an easy hotkey to just press really quick to toggle between the modes!

**Comment by LTS-FFXIV** [comment]
create in game macros and drop them on your hotbar
