### ISSUE TITLE
Dark Knight - Bloodspiller Not Being Used Under Delirium.

### ISSUE THREAD

**Issue by haganebr** [FFXIV-CombatReborn/RotationSolverReborn#20]
Title.
I'm using version 4.0.0.4.
Auto rotation pops Delirium and then keeps doing the regular 1-2-3 until it runs out without using the charges.

**Comment by LTS-FFXIV** [comment]
this is an issue with the default rotation, please reopen issue on that repo

https://github.com/FFXIV-CombatReborn/LTSDefaults

**Comment by LTS-FFXIV** [comment]
Issue fixed with 4.0.0.8 and rotation version 6.5.8.5
