### ISSUE TITLE
[Issue] Summoner Rotation Issue [AutoRotation]

### ISSUE THREAD

**Issue by meowimafruit** [FFXIV-CombatReborn/RotationSolverReborn#205]
When using the SMN Auto rotation after Solar Bahamut has been used and it comes to the rotation point Phoenix or normal Bahamut need to get used it sometimes instead wants to use Solar Bahamut, This sometimes results in the auto-rotation stopping.

Additionally it tries to use Necrotize as a oGCD even if you havent used a skill that generates stacks of aether to use the skill, this is however only a minor issue.

**Comment by IncognitoWater** [comment]
It's an issue currently linked to the gauge of the summoner not yet updated for DT can't do anything about it until it's updated...

**Comment by IncognitoWater** [comment]
Should be fixed with 7.0.1.9 release
