### ISSUE TITLE
feature request: add an option to specify keybinding in Actions and show keybinding on Control and Show Next Action Windows

### ISSUE THREAD

**Issue by KestrelWild** [FFXIV-CombatReborn/RotationSolverReborn#21]
Why?

I use the Control Window or Show Next Action Window to provide hints for what actions I should use next. It would help me react faster if I could set the keybindings for my actions and have that show up on the action icons in these windows. Would it be possible to add an option to specify the keybind in the section on the right as shown in the screenshot below?

![2024-03-29 17_45_29](https://github.com/FFXIV-CombatReborn/RotationSolverReborn/assets/10617817/64786d87-37e2-489f-9687-e2f9a2b76549)

**Comment by KestrelWild** [comment]
Example of keybinds showing on Delv CD icons: 
![2024-03-29 18_19_38](https://github.com/FFXIV-CombatReborn/RotationSolverReborn/assets/10617817/a88a1eac-d97d-4090-8234-6bf764dc1f05)

**Comment by LTS-FFXIV** [comment]
right click the icons of abilities to get macros for each of them, there is also /rotation NextAction
