### ISSUE TITLE
feature request - add an option to show cooldown sweep on the GCD action icon in Control Window

### ISSUE THREAD

**Issue by KestrelWild** [FFXIV-CombatReborn/RotationSolverReborn#22]
Could an option be added to show the cooldown sweep on the next GCD action icon in the Control Window? I find the cooldown sweep much easier to track than the GCD bar above.

Like these Delv CD icons I set up, GCD on the left showing cooldown sweep:

![2024-03-29 18_19_38](https://github.com/FFXIV-CombatReborn/RotationSolverReborn/assets/10617817/cb0bd140-5d8e-4470-bf31-2f4d055ac77b)

**Comment by NostraThomas99** [comment]
Added in #62
