### ISSUE TITLE
Rsr doesn't re-engage after phase

### ISSUE THREAD

**Issue by omfgdahoe** [FFXIV-CombatReborn/RotationSolverReborn#232]
When i tried Containment Bay Z1T9 and "killed" him before phase rsr stopped attacking at 0.1%. When the next phase began as you fall down rsr didn't re-engage and just stood there.

/edit While on top it still does the auto attacks, but after drop down nothing.
Only error/warning in logs is this :
https://kappa.lol/TO4cr.png

**Comment by LTS-FFXIV** [comment]
this is due to the boss being at 1 HP

![image](https://github.com/user-attachments/assets/2d8dcb86-e551-4c93-9549-bacfcb5eb817)
