### ISSUE TITLE
Rsr sometimes stop calculating the next attack

### ISSUE THREAD

**Issue by omfgdahoe** [FFXIV-CombatReborn/RotationSolverReborn#237]
So when I'm doing a hunt or S-rank it sometimes happens that rsr just stops attacking or rather calculating the next attack.
In the screenshot is about all info I know I could provide.
![rp19V](https://github.com/user-attachments/assets/ea1d8dfd-94d9-4ec1-8ad4-626620cc0225)

**Comment by LTS-FFXIV** [comment]
Fixed in recent update
