### ISSUE TITLE
"No rotations loaded! Please see the rotations tab!" v 7.0.1.17 BLM/BLU/VPR

### ISSUE THREAD

**Issue by matknowles** [FFXIV-CombatReborn/RotationSolverReborn#255]
Hello I've just started using this plugin and have noticed that despite loading the latest default rotations (confirmation in chat v 7.0.1.39, Culture=neutral, PublicKeyToken=Null) and a new install, it doesn't seem to recognise BLM,BLU or VPR. All other jobs load the default rotations fine (even PCT) and the rotation solver addon (not reborn) seems to recognise BLM (BLU, VPR and PCT are Unnamed though). I thought it might have something to do with having both installed (despite the non reborn one being disabled), but the issue persists even if the other plugin is disabled or deleted. I've also tried manually deleting all addon files and reinstalled just reborn, but it seems to persist.

I'd prefer to use this reborn plugin as it doesn't have any of the donowalled features and seems to be maintained more vigorously and often.

Thanks very much for all of your hard work.

**Comment by LTS-FFXIV** [comment]
![image](https://github.com/user-attachments/assets/651df719-c970-4ef3-8bd5-f21a59f43f90)

**Comment by LTS-FFXIV** [comment]
Reborn rotations do not currently support BLM/BLU/VPR as shown in the UI of the rotations menu. Yopu can find BLM and VPR rotation support with 3rd party rotations linked in the discord channel for 3rd party rotations

**Comment by matknowles** [comment]
OK sorry about that, my bad. I saw the RotationSolverReborn/RotationSolver.Basic/Rotations/Basic/BlackMageRotation.cs file and assumed I was doing something wrong.

Thanks again and keep up the good work.
