### ISSUE TITLE
[Bug?] sometimes uses egeiro without swiftcast, even when it's ready (SGE)

### ISSUE THREAD

**Issue by K0shachiyamyatA** [FFXIV-CombatReborn/RotationSolverReborn#272]
i can't reproduce this reliably. maybe boss stun mechanics, or platform falloff when the player is untargetable and therefore is interrupting the cast might cause these

![ffxiv_dx11_IJiF8efVS1](https://github.com/user-attachments/assets/9108dabb-9352-46dc-9065-f1fb1967de10)
no warnings tho

plus i think raising tank(s) and healer(s) should be higher priority than it is now. There were several situations where i had to disable auto just to res the tank so we won't wipe.

**Comment by LTS-FFXIV** [comment]
![image](https://github.com/user-attachments/assets/c77e2db4-269d-4e9a-89af-a300f0ddd4e4)
do you have this enabled?

**Comment by K0shachiyamyatA** [comment]
yes i do, but why would it not use swiftcast?

**Comment by LTS-FFXIV** [comment]
and do you have this enabled?
![image](https://github.com/user-attachments/assets/aca7185a-8721-4039-bd65-eb1173b6d57c)

**Comment by K0shachiyamyatA** [comment]
![ffxiv_dx11_FbXLgnvTm5](https://github.com/user-attachments/assets/545f4879-91ff-46f8-a8ca-24f55da172b8)
also does this option allows plugin to cancel casts? (stop dosis and use raise or heal instead, for example?)

**Comment by LTS-FFXIV** [comment]
no

**Comment by K0shachiyamyatA** [comment]
> and do you have this enabled? ![image](https://private-user-images.githubusercontent.com/127939494/352464936-aca7185a-8721-4039-bd65-eb1173b6d57c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODQ1NjgsIm5iZiI6MTcyMTk4NDI2OCwicGF0aCI6Ii8xMjc5Mzk0OTQvMzUyNDY0OTM2LWFjYTcxODVhLTg3MjEtNDAzOS1iZDY1LWViMTE3M2I2ZDU3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQwODU3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWFhZGRiMjQ4MGY1MWYzMjA2MWFjMGU4NDYzMDFhNWZkNzhiNjcyY2MxMWJlNmQ1N2I0NGRkZmNhYzlkZGVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Efl4b-Ha4cVMps_W6mvL_3K5WRAaNv7yDWQKPOYcyKc)

i can't find this

**Comment by LTS-FFXIV** [comment]
We do not do troubleshooting through github issues, for help please use the help channel in the RSR section of our discord, not through comments on issues on github. If it is determined to be a bug then please open a new issue.

**Comment by K0shachiyamyatA** [comment]
![ffxiv_dx11_BlHu7W9hge](https://github.com/user-attachments/assets/8ec3325e-be8f-4f2c-bd9f-0d45beb64775)

i found it a bit late but it's enabled

**Comment by K0shachiyamyatA** [comment]
any more options to check? Or should i open another issue?

**Comment by K0shachiyamyatA** [comment]
ok i'll test this a bit more and if it will happen again i will open another issue
