### ISSUE TITLE
[Bug] sometimes uses egeiro without swiftcast, even when it's ready (SGE)

### ISSUE THREAD

**Issue by K0shachiyamyatA** [FFXIV-CombatReborn/RotationSolverReborn#273]
i can't reproduce this reliably. maybe boss stun mechanics, or platform falloff when the player is untargetable and therefore is interrupting the cast might cause these

![ffxiv_dx11_IJiF8efVS1](https://github.com/user-attachments/assets/acfbd010-10b8-44dc-a71d-31815cc577ae)

no warnings tho

plus i think raising tank(s) and healer(s) should be higher priority than it is now. There were several situations where i had to disable auto just to res the tank so we won't wipe.

i checked all the options suggested and everything was ok, unless there are more. I didn't even change much in the config besides enabling raising when swiftcast is on the cooldown
![ffxiv_dx11_QppqGD3cdM](https://github.com/user-attachments/assets/a94f4e3c-4c74-43ee-8b46-0e73acea9fbd)
![ffxiv_dx11_BlHu7W9hge](https://github.com/user-attachments/assets/6aa979ad-1823-4222-a7d2-3df0c35fd017)

**Comment by LTS-FFXIV** [comment]
![image](https://github.com/user-attachments/assets/25b3aff8-1432-46a3-a753-443a229dffec)
disable this for now

**Comment by LTS-FFXIV** [comment]
Fixed in 7.0.1.30
