### ISSUE TITLE
[Bug] auto rotation spams actions even when it's transformed

### ISSUE THREAD

**Issue by K0shachiyamyatA** [FFXIV-CombatReborn/RotationSolverReborn#275]
![ffxiv_dx11_2Z21LbNQ1p](https://github.com/user-attachments/assets/c5caed79-d401-42c8-af67-162c06a120c7)

add support for these maybe?

**Comment by LTS-FFXIV** [comment]
"these"?

**Comment by LTS-FFXIV** [comment]
There's currently no plans to support these kind of duty actions as they are entirely context dependent
