### ISSUE TITLE
Sage - Eukrasian Diagnosis Spam

### ISSUE THREAD

**Issue by Rueby** [FFXIV-CombatReborn/RotationSolverReborn#29]
I don't think this was an issue before I switched over to this repo.
Sage constantly spams Eukrasian Diagnosis (on MT) when not in combat, it's not fishing for a crit but is just needlessly draining mana. Is there a way to disable this? Or return it to 'cast it once' sort of thing.

**Comment by LTS-FFXIV** [comment]
fixed in #30 and 4.0.0.9, please be sure to hitdownload rotations to update those as well
