### ISSUE TITLE
Add a toggle to use Medicine outside of High End Duties

### ISSUE THREAD

**Issue by Dubsys** [FFXIV-CombatReborn/RotationSolverReborn#297]
Basically currently the Medicine logic is to only use medicine in a high end duty, would it be possible to add a toggle or even a dropdown to use medicine anywhere / only in a light party / only in a full party if toggled, since there are times where you might want to use medicine outside of current savage / ultimate

https://github.com/FFXIV-CombatReborn/RotationSolverReborn/blob/70e0c29d3e9c3d7f131e8a5eef00b42895864bd3/RotationSolver.Basic/Rotations/CustomRotation_Items.cs#L28

**Comment by LTS-FFXIV** [comment]
![image](https://github.com/user-attachments/assets/c9f3728a-21d8-4498-a95f-792a3ce517bc)

fixed in 7.0.5.82
