### ISSUE TITLE
[Bug] RSR "Never attack targets with stop markers" setting not functioning as expected.

### ISSUE THREAD

**Issue by VeraNala** [FFXIV-CombatReborn/RotationSolverReborn#302]
RSR appears to be ignoring this option - or rather, it seems to _avoid_ targets with stop/ignore markers until they are the last ones remaining, and then kills them, rather than ***never*** targeting or engaging with them.
For clarity, this is with AoEType set to OFF, they are not dying from cleaves or AoE, but rather being targeted directly.
It will also attack them on pull, as a tank - but I am assuming this is done to establish Aggro, which is largely negligible.

My expected behaviour would be that when the target is marked with an ignore or stop marker, that they are removed entirely from RSR's targeting pool until the marker is removed, or changed.

**Comment by LTS-FFXIV** [comment]
What version?

**Comment by VeraNala** [comment]
v7.0.5.6 (Latest as far as I can tell)

**Comment by LTS-FFXIV** [comment]
Fixeed in 7.0.5.82
