### ISSUE TITLE
[Request] Variant Cure support

### ISSUE THREAD

**Issue by VeraNala** [FFXIV-CombatReborn/RotationSolverReborn#303]
AD is treading Variant dungeons and while some actions are represented such as Spirit Dart, the rather crucial Variant Cure skill unfortunately is not.
Would it be possible to add support for this in the near future, possibly even as an addition to the Automatic Healing Thresholds config options already present?

**Comment by LTS-FFXIV** [comment]
We have the framework for this but it was never finished, this is on the docket to be worked on after all the Jobs are up to date and functional

**Comment by LTS-FFXIV** [comment]
Fixed at some point
