### ISSUE TITLE
[Bug] BLM manaward unlock detection

### ISSUE THREAD

**Issue by K0shachiyamyatA** [FFXIV-CombatReborn/RotationSolverReborn#304]
![ffxiv_dx11_PY3zaecKRl](https://github.com/user-attachments/assets/ea299ddf-1fe0-4294-a50f-c9d09bb8f1ae)

![ffxiv_dx11_gllEJNsGJV](https://github.com/user-attachments/assets/daa1dab0-73fa-472f-9f08-418258aa4f18)
i already do have it unlocked

**Comment by CarnegieL** [comment]
That'll be because Manaward is unlocked via quest id 65889: [Garland Tools](https://garlandtools.org/db/#list/Fqp9D3gGH4). That'll need changed.

**Comment by CarnegieL** [comment]
Problem should be fixed. Please let me know

**Comment by LTS-FFXIV** [comment]
Are you on live or testing version? The fix was applied to testing version
