### ISSUE TITLE
BRD - Not casting radiant encore

### ISSUE THREAD

**Issue by meenanox** [FFXIV-CombatReborn/RotationSolverReborn#312]
The RCR when practicing on a dummy or any fight does not cast radiant encore either in its opening or in dps burst phases.

**Comment by LTS-FFXIV** [comment]
check your target settings for that action specifically

![image](https://github.com/user-attachments/assets/0b16d240-80dd-4f3b-9e2a-0da6ed5f5089)


just verified it works
