### ISSUE TITLE
[Request]Export/Import Configuration Feature

### ISSUE THREAD

**Issue by MinakataEnteh** [FFXIV-CombatReborn/RotationSolverReborn#314]
I think it’s convenient for sharing settings with friends.
I believe it’s helpful for resolving discrepancies that may arise in plugin settings.
I believe it would be beneficial to reflect settings only for items with matching names during import, and exclude those with mismatches as having inconsistencies.

I’ve been using the "Reset plugin data and reload" option quite often lately, so I would be grateful if you could consider implementing the export/import feature.

**Comment by LTS-FFXIV** [comment]
![image](https://github.com/user-attachments/assets/055ab480-d8f1-4d9a-9b2f-bde0ccf6cd32)
main menu has a button that opens your config folder for you, can manually back up files from there
