### ISSUE TITLE
[Bug] Killable bosses with 1 HP left are not attacked

### ISSUE THREAD

**Issue by Flavescent** [FFXIV-CombatReborn/RotationSolverReborn#320]
There are several bosses that receive immunity to damage once they are at 1 HP while they go through mechanics, but are then killable after the mechanics are over.

RSR recognizes the immunity and stops attacking, but then does not resume attacking the boss once they are again killable. This breaks attempts to automate such duties e.g. through Autoduty.

To reproduce, load Containment Bay Z1T9 (Extreme) with a level 100 character unsynced. Zurvan will be quickly reduced to 1 HP, but will remain alive until the phase transition. Once he reappears after the transition, still at 1 HP, he is attacking the player, but RSR is not attacking Zurvan.

**Comment by LTS-FFXIV** [comment]
This is a known consequence of the immunity protection, the game does nothing to indicate if the boss is immune or not so RSR is programmed to stop using abilities vs bosses with 1hp

**Comment by Flavescent** [comment]
Thanks - could RSR be coded to in such cases continue autoattacks or do 1-2-3 attacks or something to kill off such bosses once they become vulnerable again?

**Comment by LTS-FFXIV** [comment]
![image](https://github.com/user-attachments/assets/378e7bc4-3ce3-4f4a-94c2-35b4a5dc244f)
player toggle option added
