### ISSUE TITLE
When in windowed mode, the Teaching mode frame (which is green by default) is shifted up by one hotbar.

### ISSUE THREAD

**Issue by Ranats** [FFXIV-CombatReborn/RotationSolverReborn#322]
Like this
![image](https://github.com/user-attachments/assets/9dba408a-0a76-40ad-9c75-1e4f417551a3)

**Comment by LTS-FFXIV** [comment]
![image](https://github.com/user-attachments/assets/06fa7e91-9e1e-4647-8b57-8df1edcd3bc0)
confirmed on my side fixed
