### ISSUE TITLE
Loading incorrect Rotation

### ISSUE THREAD

**Issue by YsEmei** [FFXIV-CombatReborn/RotationSolverReborn#368]
The DSR bar correctly sees me as a Warrior while Summoner rotation is loaded. When i try fighting, nothing happens. Both Manual and Auto just stands and does nothing.

![image](https://github.com/user-attachments/assets/5c490f33-3bb6-41e2-9e49-4fe021d9a994)

If i Disable/Enable RotationSolver, it correctly loads Warrior

![image](https://github.com/user-attachments/assets/9efeabf5-9a4f-4f24-a746-0a5fe2b82c36)

My main character is Summoner. But after relogging my Warrior, it does not swap loaded rotation.

Also this sometimes: No rotations loaded. Updating doesn't load them either

![image](https://github.com/user-attachments/assets/9781329f-82a6-4e79-b494-53ab59e176b5)

**Comment by LTS-FFXIV** [comment]
please reopen if this happens in .90 or later
