### ISSUE TITLE
Rotations never loaded automatically at startup

### ISSUE THREAD

**Issue by Waitsnake** [FFXIV-CombatReborn/RotationSolverReborn#436]
After game starts with RotationSolverReborn (e.g.  7.0.5.149) the RebornRotations (7.0.5.147) are never loaded automatically.
Not sure if this is an issue or if I have just not activate the right options or if this behavior was even intended (in this cast just close this issue)?

E.g. this is direct after game start under "Loaded" no loaded rotation is visible even if option "Load rotations automatically at startup" is active. In this state "next action" will not work.
![direct_after_start](https://github.com/user-attachments/assets/599cd1ae-3147-4fd6-acff-62de70da490d)

When I then press manually on "Loaded" it loads the RebornRotations and from now on "next action" will not work.
![after_i_pressed_loaded_manually](https://github.com/user-attachments/assets/62920ead-d0fe-42a6-beea-995c400a10fc)

I just did this with my fresh generated configs from today. But I see this behavior a while ago and just ignored it.

**Comment by LTS-FFXIV** [comment]
its literally just a menu, when you click "Loaded" its expanding the menu
