### ISSUE TITLE
Exclamation mark meaning

### ISSUE THREAD

**Issue by Theletha** [FFXIV-CombatReborn/RotationSolverReborn#440]
Hi i have a exclamation mark on the status of rotation set, what does this mean? 
Wondering if there's anything that is amiss. cause on my other PC i have the icon for the class there instead.

![image](https://github.com/user-attachments/assets/5f6fe3df-50c5-46ba-ba52-d985a641cac9)

**Comment by LTS-FFXIV** [comment]
what class are you on?

**Comment by Theletha** [comment]
WAR on this one

**Comment by Theletha** [comment]
ahh it seems it was informing me that it is missing abilities since the character hadn't done the class quest yet.
