### ISSUE TITLE
BMR RSR casting/moving to target conflict

### ISSUE THREAD

**Issue by K0shachiyamyatA** [FFXIV-CombatReborn/RotationSolverReborn#450]
they yield to each other like two gentlemen at the door, and as a result, no one comes through the door

**Comment by LTS-FFXIV** [comment]
RSR is not a botting tool and is made with the intention that you are moving your character yourself.

**Comment by K0shachiyamyatA** [comment]
> RSR is not a botting tool and is made with the intention that you are moving your character yourself.

both plugins go under the same repo tho

**Comment by LTS-FFXIV** [comment]
![image](https://github.com/user-attachments/assets/c0abd8ed-0f76-4d95-a659-9404f9ffac92)

**Comment by K0shachiyamyatA** [comment]
https://github.com/FFXIV-CombatReborn/BossmodReborn/issues/458
