### ISSUE TITLE
Stun actions not being used on melee DPS jobs INSIDE of duties.

### ISSUE THREAD

**Issue by AnonLoid** [FFXIV-CombatReborn/RotationSolverReborn#46]
Hi.
Im using LTS rotation with MNK and RPR, and notice strange thing, in world stun actions used correctly (if mob tries to aoe and i can interrupt him), but with the same conditions, RS dont stun mobs in dungeons, when they perfrorm AOE attacks. I still manually can stun them.

**Comment by LTS-FFXIV** [comment]
Just verified my monk used Leg Sweep vs a boss in Void Ark, stun actions are used in duty

**Comment by AnonLoid** [comment]
Confirmed, somehow it was fixed in the updates.
