### ISSUE TITLE
Only attack target in vision cone also limits healing

### ISSUE THREAD

**Issue by Xeltor** [FFXIV-CombatReborn/RotationSolverReborn#49]
When you enable "Only attack the targets in vision cone" as any healer it also limits healing to the vision cone.

I don't know if this is intended but this never used to be the case.

![afbeelding](https://github.com/FFXIV-CombatReborn/RotationSolverReborn/assets/702588/e26f40d7-f781-4220-9b18-3cc83693aede)

**Comment by NostraThomas99** [comment]
This is intentional. With targeting being genericized the heal targets and damage targets are handled the same. If it's a big enough problem I can try and rework it or at least make that setting class specific.

**Comment by LTS-FFXIV** [comment]
Nostra is correct this is intentional, closing also please remove image, do not include images with player names.
