### ISSUE TITLE
[MNK] Rotation never do phantom rush in the 2 min cd

### ISSUE THREAD

**Issue by Delky91** [FFXIV-CombatReborn/RotationSolverReborn#491]
hi, look first time here, i have my GF that she born witouth a full hand, so i introduce to she this plugins so she can play with me, and she is very happy, today i was checking the rotation that the RSR do and i find that for monk, the rotation start with a rising phoenix always and then go for elixir burst, so this bring the problem that in the odd minutes is when is using phantom rush outside all buff, any chance to configurate so the RSR can start with doble lunar for example, other autorotation do the doble lunar but are no so good like RSR, another probles is that every time the rsr break the rotation for using the opo stance, even without the buff in the stance breaking hte combos. tyvm for doing this plugin my GF is happy that she can play with me

**Comment by LTS-FFXIV** [comment]
issues noted here fixed with 7.1.5.11
