### ISSUE TITLE
AoE abilities no longer trigger in Manual mode

### ISSUE THREAD

**Issue by PlasticMood** [FFXIV-CombatReborn/RotationSolverReborn#50]
Before last night's maintenance, I was using manual mode with the 'Use AoE actions in manual mode' setting enabled, and it worked perfectly. However, after logging in today, it appears to no longer function. Everything operates as expected in Auto mode, but I prefer using manual mode with the AoE option.

**Comment by LTS-FFXIV** [comment]
![image](https://github.com/FFXIV-CombatReborn/RotationSolverReborn/assets/127939494/aae17087-5bd8-45b5-ad03-3da0a862368b)

**Comment by LTS-FFXIV** [comment]
this setting right? i just tested across 3 characters and verified it works

**Comment by LTS-FFXIV** [comment]
in the discord FAQ channel theres reset instructions

**Comment by rossen-kostov** [comment]
Thanks, I followed the reset instructions and tried again, and still not getting AoE actions in manual mode. I appreciate your help, but I guess I'll just have to deal with it.

**Comment by NostraThomas99** [comment]
Fixed in PR #55
