### ISSUE TITLE
Some PvP skills are not activated.

### ISSUE THREAD

**Issue by KouGithub2022** [FFXIV-CombatReborn/RotationSolverReborn#52]
I am writing code for a PvP rotation, but some skills are not activated.

MCHPvP:BishopAutoturretPvP
SMN:SummonBahamutPvP,SummonPhoenixPvP
    (public static IBaseAction SummonBahamutPvP { get; } = new BaseAction((ActionID)29673);)
    (public static IBaseAction SummonPhoenixPvP { get; } = new BaseAction((ActionID)29678);)

**Comment by NostraThomas99** [comment]
These are limit breaks, correct? What do you mean exactly when you say they're not activated?

**Comment by Tykku** [comment]
Bishop is not an LB, the other 2 are

**Comment by NostraThomas99** [comment]
There's a known issue with limit breaks where they're not being made public to rotations. It's on my list to fix. You should still be able to define them manuall, though (As you did here:
`public static IBaseAction SummonPhoenixPvP { get; } = new BaseAction((ActionID)29678);`

**Comment by NostraThomas99** [comment]
Although you may have better luck with just:
`IBaseAction SummonPhoenixPvP = new BaseAction((ActionID)29678));`

**Comment by KouGithub2022** [comment]
The translation is wrong.
It doesn't work.

Is there a problem with the installation skills?
DRK's Shadowbringer is forcing me to move it, which gives me the same symptoms as in 3.6.3.0.

**Comment by NostraThomas99** [comment]
I really need more to go on than "it doesn't work". Does the ability fail to fire? Does your code fail to compile? Do you get any error messages?

As I said above, there is currently an issue where Limit Breaks specifically cannot be referenced from the source gen code. This will be fixed in the next release.

**Comment by KouGithub2022** [comment]
I can build it and it just won't start without any errors.

**Comment by ArchiDog1998** [comment]
`LimitBreakPvP` property.

**Comment by NostraThomas99** [comment]
Fixed in #54
