### ISSUE TITLE
Feature Request: Possible Off Tank Situation And Maybe Allowing /rotation DoAction Command To Trigger Disabled Action

### ISSUE THREAD

**Issue by oorinx** [FFXIV-CombatReborn/RotationSolverReborn#60]
_Woop that was a long title._

- I have been trying out tank in duties and find out every time I load into a duty, the rotation automatically turns on tank stance. Tried turning it off, it instantly turn it back on. Issue being, it is impossible to play as Off Tank with RSR. ( Possible rotation optimization issue instead of RSR issue )
- Because of the above issue, i disabled the action in Action list and hence I can't trigger the action using /rotation DispelStancePositional . Need to use vanilla action button to trigger the action.
- Possibly a better automation setting for Provoke, so it does not spam Provoke on cases like Off Tank / Alliance Raid / Hunts where multiple tanks exist attacking the same mob.

Thank you :D

**Comment by Tykku** [comment]
What tank

**Comment by oorinx** [comment]
> What tank

Dont think that matters since the issue is for role skill? 
Tank stance , Shirk, Provoke

But to answer your question, i tried it with all tanks and they all do the same auto turn on tank stance when i manually turn the stance off.

**Comment by LTS-FFXIV** [comment]
Turn off automatic tank stance and automatic provoke, they are specific settings rather than disabling the abilities themselves.

**Comment by LTS-FFXIV** [comment]
![image](https://github.com/FFXIV-CombatReborn/RotationSolverReborn/assets/127939494/88e8eb1d-910a-458f-8ed7-c72b8d764c79)
