### ISSUE TITLE
Feature request or bug: Implementing variant actions

### ISSUE THREAD

**Issue by Flavescent** [FFXIV-CombatReborn/RotationSolverReborn#61]
Variant actions (the selectable duty actions available in variant dungeons, e.g. Variant Rampart, Variant Cure) appear to be broken or unimplemented at the moment (RSR v4.0.0.22). Even while in a variant dungeon (e.g. Mount Rokkon) with such actions available to the player as duty actions, these actions do not show up in Rotation Solver's action list, and can't therefore be invoked via conditions. They are also apparently not part of any rotation.

Because variant actions are part of the intended gameplay for variant dungeons, especially solo, I'd greatly appreciate it if someone were to implement them. Most can and should be cast basically on cooldown, so no much work should be required to make them fit into rotations.

**Comment by LTS-FFXIV** [comment]
fixed in recent update
