### ISSUE TITLE
Feature request and a bugfix: implement anti-kb abilities

### ISSUE THREAD

**Issue by AnonLoid** [FFXIV-CombatReborn/RotationSolverReborn#64]
Yo! 
I will know that RS learns on new abilities that been used by mobs in dungeons, and must use mits for it.
RN its not working, because my list is the same (list>actions) as i installed RS. Or RS do not displaying that it learns something.
My idea is fix this list thing if its broken, and let RS remembor what AOE/KB/TB hit it and next time, when same ability being cast from mob, RS will use antikb/mits/etc to prevent getting hit.

(also, Nostra, sleep at least 8 hours pls)

**Comment by LTS-FFXIV** [comment]
AOEs are the only things recorded, not tankbusters or knockbacks as RS pulls the information for those straight from the game as the casts are happening. if you want to ensure a anti knockback is used use the command below

/rotation AntiKnockback

**Comment by NostraThomas99** [comment]
It should be possible to reimplement the AoE logic into both tankbusters and knockbacks. RSR will always miss the first instance of these types of attacks, but it can "learn" from itself, record the action IDs and auto use mits/antiknockbacks when it spots those actionIDs again.
