### ISSUE TITLE
Add IsOpener flag to CustomRotation

### ISSUE THREAD

**Issue by NostraThomas99** [FFXIV-CombatReborn/RotationSolverReborn#65]
Rotations should have an IsOpener flag that the framework sets to true on combat start. The rotation can then operate under different logic conditions until it decides to set this flag back to false on its own.

**Comment by Tykku** [comment]
Drool......................yes please

**Comment by NostraThomas99** [comment]
On further investigation, it may make more sense for this to be implemented at the rotation level. CustomRotation already exposes CombatTime, so the rotation writer can do something like:

`if (CombatTime <= 30) DoOpenerChecks();`

The rotation can then check statuses, apply buffs do whatever it needs to.
