### ISSUE TITLE
WHM heals broken completely, RS using only AOE heals.

### ISSUE THREAD

**Issue by AnonLoid** [FFXIV-CombatReborn/RotationSolverReborn#70]
Yo!
Strange behavior on WHM on last build.
On LTS rotation in auto mode it uses only liturgy for heal, thats all, nothing else, just glare the fuck out of boss.
On Maru its liturgy and medica and still glares.
It does not benediction/regen/cure/solace on some party member, does not mit aoes.
Just constantly dpsing and let the party members die, even player with rs get ignored and died, no self heal at all.

**Comment by Rabalaba** [comment]
are you using auto or manual target mode?

**Comment by AnonLoid** [comment]
Problem was on my side, wrong autoheal settings.

**Comment by LTS-FFXIV** [comment]
Please share the settings for future reference
