### ISSUE TITLE
Bug: Friendly duty NPCs are not targets of heal actions

### ISSUE THREAD

**Issue by Flavescent** [FFXIV-CombatReborn/RotationSolverReborn#82]
In healer job quests, players need to keep certain NPCs alive. But as of v4.0.2.3, RSR won't target them for heals, probably because it thinks of them as NPCs rather than party members. This leads to the NPCs dying and the duty failing.

Even with the targeting options "Target allies for friendly actions" and "Target all for friendly actions", the NPCs are not being actively healed. With only the first option enabled, the NPCs are apparently never targeted for healer actions. With both options enabled, the NPCs are targeted for certain protective actions (eg Eukrasian Diagnosis), but apparently not actively healed, or at least not prioritized for survival the way a party tank would be.

To reproduce, do the first SGE job quest (Sage's Focus) on an alt character, and enter the tutorial duty with Lalah Jinjahl. Remove Kardia from her and confront the second mob pack with RSR active. The player SGE will only cast offensive actions and let Lalah die.

**Comment by Tykku** [comment]
Stale issue
