### ISSUE TITLE
AoE in manual mode

### ISSUE THREAD

**Issue by Kery0x** [FFXIV-CombatReborn/RotationSolverReborn#9]
Hey, i did a clean reinstall of the new version, and my warrior is using aoe on manual settings, tho i have this option disabled

![ffxiv_dx11_Tw9nK4mdyk](https://github.com/FFXIV-CombatReborn/RotationSolverReborn/assets/121441173/7d82e601-48a0-4020-b2b6-81ef34492ebd)

also aoe is correctly greyed out on the control panel

![ffxiv_dx11_5PKPxt5esm](https://github.com/FFXIV-CombatReborn/RotationSolverReborn/assets/121441173/23b6c19d-5113-4c07-bf2f-dc2062593efc)

I did not find any workaround for now

I'm on rotation solver 4.0.0.1

**Comment by NostraThomas99** [comment]
Fixed in PR #14
